# Generated by Django 2.1.2 on 2020-02-08 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(blank=True, max_length=200)),
                ('cookie_value', models.CharField(default='', max_length=200)),
                ('signup_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
