# Generated by Django 3.0.3 on 2020-03-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='email',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='name_id',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
