# Generated by Django 2.1.2 on 2020-02-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='address',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
