# Generated by Django 3.0 on 2020-02-26 10:18

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='votecnt',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='Type',
            field=models.IntegerField(choices=[(1, 'Learning'), (2, 'Interview'), (3, 'Exercise')]),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.Visitor')),
            ],
        ),
    ]
