# Generated by Django 3.0 on 2020-02-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200208_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
