# Generated by Django 2.1.2 on 2020-02-02 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='title',
        ),
    ]
