# Generated by Django 3.0 on 2020-02-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200209_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Type',
            field=models.IntegerField(choices=[(1, 'Learning'), (2, 'Interview'), (3, 'Exercise')]),
        ),
    ]
